name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    # Format the output of dotnet format
    - name: Add dotnet-format problem matcher
      uses: xt0rted/dotnet-format-problem-matcher@v1

    # Install dotnet format as a global tool
    - name: Install dotnet format
      run: dotnet tool update --global dotnet-format

    # Run dotnet format --dry-run --check
    # By default, the task ensure the exit code is 0
    # If a file needs to be edited by dotnet format, the exit code will be a non-zero value
    # So the task will fail
    - name: Run dotnet format
      run: dotnet format --check --verbosity diagnostic

    - name: Restore dependencies
      run: dotnet restore

    # From https://github.com/dotnet/code-analysis
    # TODO Fix this later
    # - name: Run .NET Code Analysis
    #   uses: dotnet/code-analysis@v1
    #   id: code-analysis
    #   with:
    #     # solution: MySolution.sln
    #     project: min_web_dotnet_6.csproj
    #     build-breaking: true
    #     all-categories: all

    - name: Build
      run: dotnet build --no-restore -warnAsError
    - name: Test
      run: dotnet test --no-build --verbosity normal
